{
 "title": "Historical Sessions",
 "time": { "from": "2023-10-07T18:43:34.387Z", "to": "2023-10-07T18:45:40.777Z" },
 "templating": {
  "list": [
   {
    "name": "getDevices",
    "query": "SELECT DISTINCT device FROM mqtt_consumer;\n"
   },
   {
    "name": "getSessionIds",
    "query": "SELECT DISTINCT sessionid FROM mqtt_consumer \norder by sessionid desc;"
   }
  ]
 },
 "panels": [
  {
   "title": "RMSE_MODE",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH measurements AS (\r\n    SELECT \r\n        latitude, \r\n        longitude, \r\n        sessionid,\r\n        device\r\n    FROM \r\n        mqtt_consumer\r\n    WHERE \r\n        sessionid = 42\r\n        AND device IN ('94:B9:7E:13:BF:EB', '58:BF:25:DA:15:49', '00:1E:42:2B:9C:13')\r\n),\r\nreference_data AS (\r\n    SELECT \r\n         MODE() WITHIN GROUP (ORDER BY latitude) AS modal_latitude,\r\n        MODE() WITHIN GROUP (ORDER BY longitude) AS modal_longitude\r\n    FROM \r\n        mqtt_consumer\r\n    WHERE \r\n        sessionid = 39\r\n),\r\nconverted_measurements AS (\r\n    SELECT\r\n        device,\r\n        ST_Transform(\r\n            ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),\r\n            32633) AS utm_measurements_point,\r\n        ST_X(\r\n            ST_Transform(\r\n                ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),\r\n                32633)) AS utm_measurements_x,\r\n        ST_Y(\r\n            ST_Transform(\r\n                ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),\r\n                32633)) AS utm_measurements_y\r\n    FROM \r\n        measurements\r\n),\r\nconverted_reference_data AS (\r\n    SELECT\r\n        ST_Transform(\r\n            ST_SetSRID(ST_MakePoint(modal_longitude, modal_latitude), 4326),\r\n            32633) AS utm_reference_point,\r\n        ST_X(\r\n            ST_Transform(\r\n                ST_SetSRID(ST_MakePoint(modal_longitude, modal_latitude), 4326),\r\n                32633)) AS utm_reference_x,\r\n        ST_Y(\r\n            ST_Transform(\r\n                ST_SetSRID(ST_MakePoint(modal_longitude, modal_latitude), 4326),\r\n                32633)) AS utm_reference_y\r\n    FROM \r\n        reference_data\r\n)\r\nSELECT\r\n    device,\r\n    (SQRT(AVG(POWER(CAST(utm_measurements_x AS numeric) - utm_reference_x, 2))) + SQRT(AVG(POWER(CAST(utm_measurements_y AS numeric) - utm_reference_y, 2)))) AS drms_radius,\r\n    2 * (SQRT(AVG(POWER(CAST(utm_measurements_x AS numeric) - utm_reference_x, 2))) + SQRT(AVG(POWER(CAST(utm_measurements_y AS numeric) - utm_reference_y, 2)))) AS twodrms_radius,\r\n    0.62 * SQRT(AVG(POWER(CAST(utm_measurements_x AS numeric) - utm_reference_x, 2))) + 0.56 * SQRT(AVG(POWER(CAST(utm_measurements_y AS numeric) - utm_reference_y, 2))) AS cep_radius\r\nFROM \r\n    converted_measurements\r\nJOIN \r\n    converted_reference_data ON 1=1\r\nGROUP BY \r\n    device;\r\n"
    }
   ]
  },
  {
   "title": "RMSE_AVERAGE",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH measurements AS (\r\n    SELECT \r\n        latitude, \r\n        longitude, \r\n        sessionid,\r\n        device\r\n    FROM \r\n        mqtt_consumer\r\n    WHERE \r\n        sessionid = 42\r\n     \r\n),\r\nreference_data AS (\r\n    SELECT \r\n         MODE() WITHIN GROUP (ORDER BY latitude) AS modal_latitude,\r\n        MODE() WITHIN GROUP (ORDER BY longitude) AS modal_longitude\r\n    FROM \r\n        mqtt_consumer\r\n    WHERE \r\n        sessionid = 39\r\n),\r\nconverted_measurements AS (\r\n    SELECT\r\n        device,\r\n        ST_Transform(\r\n            ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),\r\n            32633) AS utm_measurements_point,\r\n        ST_X(\r\n            ST_Transform(\r\n                ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),\r\n                32633)) AS utm_measurements_x,\r\n        ST_Y(\r\n            ST_Transform(\r\n                ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),\r\n                32633)) AS utm_measurements_y\r\n    FROM \r\n        measurements\r\n),\r\nconverted_reference_data AS (\r\n    SELECT\r\n        ST_Transform(\r\n            ST_SetSRID(ST_MakePoint(modal_longitude, modal_latitude), 4326),\r\n            32633) AS utm_reference_point,\r\n        ST_X(\r\n            ST_Transform(\r\n                ST_SetSRID(ST_MakePoint(modal_longitude, modal_latitude), 4326),\r\n                32633)) AS utm_reference_x,\r\n        ST_Y(\r\n            ST_Transform(\r\n                ST_SetSRID(ST_MakePoint(modal_longitude, modal_latitude), 4326),\r\n                32633)) AS utm_reference_y\r\n    FROM \r\n        reference_data\r\n)\r\nSELECT\r\n    device,\r\n    (SQRT(AVG(POWER(CAST(utm_measurements_x AS numeric) - utm_reference_x, 2))) + SQRT(AVG(POWER(CAST(utm_measurements_y AS numeric) - utm_reference_y, 2)))) AS drms_radius,\r\n    2 * (SQRT(AVG(POWER(CAST(utm_measurements_x AS numeric) - utm_reference_x, 2))) + SQRT(AVG(POWER(CAST(utm_measurements_y AS numeric) - utm_reference_y, 2)))) AS twodrms_radius,\r\n    0.62 * SQRT(AVG(POWER(CAST(utm_measurements_x AS numeric) - utm_reference_x, 2))) + 0.56 * SQRT(AVG(POWER(CAST(utm_measurements_y AS numeric) - utm_reference_y, 2))) AS cep_radius\r\nFROM \r\n    converted_measurements\r\nJOIN \r\n    converted_reference_data ON 1=1\r\nGROUP BY \r\n    device;\r\n"
    }
   ]
  },
  {
   "title": "mode",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT  mode() WITHIN GROUP (ORDER BY latitude ) AS modal_latitude  FROM mqtt_consumer mc  where  sessionid = $getSessionIds "
    },
    {
     "rawSql": "SELECT  mode() WITHIN GROUP (ORDER BY longitude) AS modal_longitude  FROM mqtt_consumer mc  where  sessionid = $getSessionIds "
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, latitude, longitude\r\nFROM mqtt_consumer where sessionid = $getSessionIds \r\n\r\n"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, \"time\" FROM mqtt_consumer WHERE device = '$getDevices' and sessionid = $getSessionIds "
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, latitude FROM mqtt_consumer WHERE sessionid = $getSessionIds "
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, longitude FROM mqtt_consumer WHERE sessionid = $getSessionIds "
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, altitude  FROM mqtt_consumer WHERE sessionid = $getSessionIds "
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, speed FROM mqtt_consumer WHERE sessionid = $getSessionIds "
    }
   ]
  },
  {
   "title": "Satellites",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, satellites FROM mqtt_consumer WHERE sessionid = $getSessionIds "
    }
   ]
  }
 ]
}