{
 "title": "Recent Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "getDevices",
    "query": "SELECT DISTINCT device FROM mqtt_consumer;"
   },
   { "name": "GetTime", "query": "5,15,30,60" }
  ]
 },
 "panels": [
  {
   "title": "Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, latitude, longitude\r\nFROM mqtt_consumer where \"time\" >= NOW() - INTERVAL '$GetTime minutes';\r\n\r\n"
    }
   ]
  },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, \"time\" FROM mqtt_consumer WHERE device = '$getDevices' and  \"time\" >= NOW() - INTERVAL '$GetTime minutes';"
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, latitude FROM mqtt_consumer WHERE \"time\" >= NOW() - INTERVAL '$GetTime minutes';\r\n"
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, longitude FROM mqtt_consumer  where \"time\" >= NOW() - INTERVAL '$GetTime minutes';"
    }
   ]
  },
  {
   "title": "Satellites",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, satellites FROM mqtt_consumer  where \"time\" >= NOW() - INTERVAL '$GetTime minutes';\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, speed FROM mqtt_consumer  where \"time\" >= NOW() - INTERVAL '$GetTime minutes';"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", device, altitude  FROM mqtt_consumer  where \"time\" >= NOW() - INTERVAL '$GetTime minutes';"
    }
   ]
  }
 ]
}